# Generated by Django 3.0.5 on 2020-04-13 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recruitment_app.short_url


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LongURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('longurl', models.URLField(blank=True, unique=True)),
                ('shorturl', models.URLField(blank=True, default=recruitment_app.short_url.shorten_url)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='longurl', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
